PART 7 - MACHINE LEARNING: SUPERVISED LEARNING

Additional Data Preparation Before modeling

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("flight_price_data.csv")
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [5]:
## one hot encoding
## adalah proses mengubah variabel kategorikal menjadi variabel numerik

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [8]:
df_obj = df.select_dtypes(["object"])
col_obj = df_obj.columns
col_obj

Index(['airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class'],
      dtype='object')

In [10]:
df_clean = pd.get_dummies(df, columns=col_obj)
df_clean

,Unnamed: 0,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,...,arrival_time_Morning,arrival_time_Night,destination_city_Bangalore,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_Business,class_Economy
0,0,2.17,1,5953,False,False,False,False,True,False,...,False,True,False,False,False,False,False,True,False,True
1,1,2.33,1,5953,False,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
2,2,2.17,1,5956,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
3,3,2.25,1,5955,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,True
4,4,2.33,1,5955,False,False,False,False,False,True,...,True,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,10.08,49,69265,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False
300149,300149,10.42,49,77105,False,False,False,False,False,True,...,False,True,False,False,False,True,False,False,True,False
300150,300150,13.83,49,79099,False,False,False,False,False,True,...,False,True,False,False,False,True,False,False,True,False
300151,300151,10.00,49,81585,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False
300152,300152,10.08,49,81585,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False

In [ ]:
## train test split
## adalah proses membagi dataset menjadi dua bagian, yaitu data latih dan data uji
## data train digunakan untuk melatih model, sedangkan data test digunakan untuk menguji model
from sklearn.model_selection import train_test_split
## y adalah target dan x adalah input
y = df_clean["price"]
x = df_clean.drop(columns=["price"])

In [15]:
y

0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [16]:
x

,Unnamed: 0,duration,days_left,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,flight_6E-102,...,arrival_time_Morning,arrival_time_Night,destination_city_Bangalore,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_Business,class_Economy
0,0,2.17,1,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,True,False,True
1,1,2.33,1,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,True,False,True
2,2,2.17,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
3,3,2.25,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,True
4,4,2.33,1,False,False,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,10.08,49,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
300149,300149,10.42,49,False,False,False,False,False,True,False,...,False,True,False,False,False,True,False,False,True,False
300150,300150,13.83,49,False,False,False,False,False,True,False,...,False,True,False,False,False,True,False,False,True,False
300151,300151,10.00,49,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
300152,300152,10.08,49,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size= 0.3, random_state=1)

In [19]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(210107, 1599)
(90046, 1599)
(210107,)
(90046,)

In [21]:
## regression case study
from sklearn import linear_model

In [22]:
linear_reg = linear_model.LinearRegression()

linear_reg.fit(X_train, Y_train)

LinearRegression()

In [23]:
print("intercept:", linear_reg.intercept_)

intercept: 38435.99665010096

In [30]:
##evaluasi model
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

y_pred = linear_reg.predict(X_test)

In [26]:
mean_absolute_error(Y_test, y_pred)

4225.936576594232

In [32]:
root_mean_squared_error(Y_test, y_pred)

6128.272697587725

In [34]:
import numpy as np
print(np.mean(Y_test))
print(np.std(Y_test))

20810.64765786376
22662.845864088857

In [36]:
r2_score(Y_test, y_pred)

0.926878132470053