PART 7 - MACHINE LEARNING: SUPERVISED LEARNING

Additional Data Preparation Before modeling

In [4]:
import pandas as pd

In [4]:
df = pd.read_csv("flight_price_data.csv")
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [5]:
## one hot encoding
## adalah proses mengubah variabel kategorikal menjadi variabel numerik

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [8]:
df_obj = df.select_dtypes(["object"])
col_obj = df_obj.columns
col_obj

Index(['airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class'],
      dtype='object')

In [10]:
df_clean = pd.get_dummies(df, columns=col_obj)
df_clean

,Unnamed: 0,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,...,arrival_time_Morning,arrival_time_Night,destination_city_Bangalore,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_Business,class_Economy
0,0,2.17,1,5953,False,False,False,False,True,False,...,False,True,False,False,False,False,False,True,False,True
1,1,2.33,1,5953,False,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
2,2,2.17,1,5956,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
3,3,2.25,1,5955,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,True
4,4,2.33,1,5955,False,False,False,False,False,True,...,True,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,10.08,49,69265,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False
300149,300149,10.42,49,77105,False,False,False,False,False,True,...,False,True,False,False,False,True,False,False,True,False
300150,300150,13.83,49,79099,False,False,False,False,False,True,...,False,True,False,False,False,True,False,False,True,False
300151,300151,10.00,49,81585,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False
300152,300152,10.08,49,81585,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False

In [ ]:
## train test split
## adalah proses membagi dataset menjadi dua bagian, yaitu data latih dan data uji
## data train digunakan untuk melatih model, sedangkan data test digunakan untuk menguji model
from sklearn.model_selection import train_test_split
## y adalah target dan x adalah input
y = df_clean["price"]
x = df_clean.drop(columns=["price"])

In [15]:
y

0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [16]:
x

,Unnamed: 0,duration,days_left,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,flight_6E-102,...,arrival_time_Morning,arrival_time_Night,destination_city_Bangalore,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_Business,class_Economy
0,0,2.17,1,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,True,False,True
1,1,2.33,1,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,True,False,True
2,2,2.17,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
3,3,2.25,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,True
4,4,2.33,1,False,False,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,10.08,49,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
300149,300149,10.42,49,False,False,False,False,False,True,False,...,False,True,False,False,False,True,False,False,True,False
300150,300150,13.83,49,False,False,False,False,False,True,False,...,False,True,False,False,False,True,False,False,True,False
300151,300151,10.00,49,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
300152,300152,10.08,49,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size= 0.3, random_state=1)

In [19]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(210107, 1599)
(90046, 1599)
(210107,)
(90046,)

In [21]:
## regression case study
from sklearn import linear_model

In [32]:
linear_reg = linear_model.LinearRegression()

linear_reg.fit(X_train, Y_train)

NameError: name 'linear_model' is not defined

In [23]:
print("intercept:", linear_reg.intercept_)

intercept: 38435.99665010096

In [30]:
##evaluasi model
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

y_pred = linear_reg.predict(X_test)

In [26]:
mean_absolute_error(Y_test, y_pred)

4225.936576594232

In [32]:
root_mean_squared_error(Y_test, y_pred)

6128.272697587725

In [34]:
import numpy as np
print(np.mean(Y_test))
print(np.std(Y_test))

20810.64765786376
22662.845864088857

In [36]:
r2_score(Y_test, y_pred)

0.926878132470053

In [5]:
##classificaiton case study
df = pd.read_csv("telco_costumer.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [9]:
##change data type
df = df[~(df["TotalCharges"] == " ")]

df["TotalCharges"] = df["TotalCharges"].astype("float64")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [12]:
## one hot encoding
## adalah proses mengubah beberapa type object menjadi numerik tujuhnya agar bisa digunakan dalam model
df_obj = df.select_dtypes(["object"])
col_obj = list(df_obj.columns)
col_obj.remove("customerID")
col_obj.remove("Churn")

In [14]:
df_clean = pd.get_dummies(df, columns=col_obj)
df_clean

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,1,29.85,29.85,No,True,False,False,True,...,False,True,False,False,False,True,False,False,True,False
1,5575-GNVDE,0,34,56.95,1889.50,No,False,True,True,False,...,False,False,True,False,True,False,False,False,False,True
2,3668-QPYBK,0,2,53.85,108.15,Yes,False,True,True,False,...,False,True,False,False,False,True,False,False,False,True
3,7795-CFOCW,0,45,42.30,1840.75,No,False,True,True,False,...,False,False,True,False,True,False,True,False,False,False
4,9237-HQITU,0,2,70.70,151.65,Yes,True,False,True,False,...,False,True,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,24,84.80,1990.50,No,False,True,False,True,...,True,False,True,False,False,True,False,False,False,True
7039,2234-XADUH,0,72,103.20,7362.90,No,True,False,False,True,...,True,False,True,False,False,True,False,True,False,False
7040,4801-JZAZL,0,11,29.60,346.45,No,True,False,False,True,...,False,True,False,False,False,True,False,False,True,False
7041,8361-LTMKD,1,4,74.40,306.60,Yes,False,True,False,True,...,False,True,False,False,False,True,False,False,False,True
7042,3186-AJIEK,0,66,105.65,6844.50,No,False,True,True,False,...,True,False,False,True,False,True,True,False,False,False

In [15]:
## train test split
## adalah proses membagi dataset menjadi dua bagian, yaitu data latih dan data uji
from sklearn.model_selection import train_test_split

In [18]:
y = df_clean["Churn"].map({"Yes": 1, "No": 0})
x = df_clean.drop(columns=["Churn"])

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [20]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(4922, 46)
(2110, 46)
(4922,)
(2110,)

In [22]:
## imbalance data
## adalah kondisi di mana jumlah data pada setiap kelas tidak seimbang
Y_train.value_counts()

Churn
0    3608
1    1314
Name: count, dtype: int64

In [24]:
from sklearn.utils import resample

df_train = pd.concat([X_train, Y_train], axis=1)

df_majority = df_train[df_train["Churn"] == 0]
df_minority = df_train[df_train["Churn"] == 1]

df_minority_upsampled = resample(df_minority, replace=True, n_samples=3608, random_state=1)

df_train_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [25]:
df_train_upsampled["Churn"].value_counts()

Churn
0    3608
1    3608
Name: count, dtype: int64

In [27]:
Y_train_upsampled = df_train_upsampled["Churn"]
X_train_upsampled = df_train_upsampled.drop(columns=["Churn"])

In [28]:
## remove column customerID
X_train = X_train.drop(columns=["customerID"])
X_train_upsampled = X_train_upsampled.drop(columns=["customerID"])

In [31]:
## logistic regression
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, Y_train)

log_reg_up = LogisticRegression()
log_reg_up.fit(X_train_upsampled, Y_train_upsampled)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [34]:
## decission tree
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, Y_train)

dt_up = DecisionTreeClassifier()
dt_up.fit(X_train_upsampled, Y_train_upsampled)

DecisionTreeClassifier()

In [35]:
## random forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, Y_train)

rf_up = RandomForestClassifier()
rf_up.fit(X_train_upsampled, Y_train_upsampled)

RandomForestClassifier()

In [36]:
params = {
    "max_depth": [2, 3, 5, 10, 15],
    "min_samples_leaf": [15, 30, 50, 100, 150]
}

In [37]:
rf_base = RandomForestClassifier()

In [38]:
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(estimator=rf_base, param_grid=params, cv=5, scoring="roc_auc")

In [39]:
grid_search.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [2, 3, 5, 10, 15],
                         'min_samples_leaf': [15, 30, 50, 100, 150]},
             scoring='roc_auc')

In [40]:
rf_base = grid_search.best_estimator_
rf_base.fit(X_train, Y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=15)

In [41]:
grid_search.fit(X_train_upsampled, Y_train_upsampled)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [2, 3, 5, 10, 15],
                         'min_samples_leaf': [15, 30, 50, 100, 150]},
             scoring='roc_auc')

In [42]:
rf_base_up = grid_search.best_estimator_
rf_base_up.fit(X_train_upsampled, Y_train_upsampled)

RandomForestClassifier(max_depth=15, min_samples_leaf=15)

In [43]:
log_reg

LogisticRegression()

In [44]:
log_reg_up

LogisticRegression()

In [45]:
dt

DecisionTreeClassifier()

In [46]:
dt_up

DecisionTreeClassifier()

In [47]:
rf

RandomForestClassifier()

In [48]:
rf_up

RandomForestClassifier()

In [49]:
rf_base

RandomForestClassifier(max_depth=10, min_samples_leaf=15)

In [50]:
rf_base_up

RandomForestClassifier(max_depth=15, min_samples_leaf=15)

In [ ]:
## prediction x-test
y_lr = log_reg.predict(X_test)
y_lr_up = log_reg_up.predict(X_test)
y_dt = dt.predict(X_test)
y_dt_up = dt_up.predict(X_test)
y_rf = rf.predict(X_test)
y_rf_up = rf_up.predict(X_test)
y_rf_base = rf_base.predict(X_test)
y_rf_base_up = rf_base_up.predict(X_test)

In [55]:
## Evaluasi Model

In [60]:
## precision
from sklearn.metrics import precision_score

precision_lr = precision_score(Y_test, y_lr, pos_label=1, average="binary")
precision_lr_up = precision_score(Y_test, y_lr_up, pos_label=1, average="binary")
precision_dt = precision_score(Y_test, y_dt, pos_label=1, average="binary")
precision_dt_up = precision_score(Y_test, y_dt_up, pos_label=1, average="binary")
precision_rf = precision_score(Y_test, y_rf, pos_label=1, average="binary")
precision_rf_up = precision_score(Y_test, y_rf_up, pos_label=1, average="binary")
precision_base = precision_score(Y_test, y_rf_base, pos_label=1, average="binary")
precision_base_up = precision_score(Y_test, y_rf_base_up, pos_label=1, average="binary")

print("precision lr:", precision_lr)
print("precision lr up:", precision_lr_up)
print("precision dt:", precision_dt)
print("precision dt up:", precision_dt_up)
print("precision rf:", precision_rf)
print("precision rf up:", precision_rf_up)
print("precision base:", precision_base)
print("precision base up:", precision_base_up)

precision lr: 0.6440677966101694
precision lr up: 0.5188679245283019
precision dt: 0.4771986970684039
precision dt up: 0.5080500894454383
precision rf: 0.6112412177985949
precision rf up: 0.5625
precision base: 0.6725888324873096
precision base up: 0.5216867469879518

In [61]:
## recall
from sklearn.metrics import recall_score

recall_lr = recall_score(Y_test, y_lr, pos_label=1, average="binary")
recall_lr_up = recall_score(Y_test, y_lr_up, pos_label=1, average="binary")
recall_dt = recall_score(Y_test, y_dt, pos_label=1, average="binary")
recall_dt_up = recall_score(Y_test, y_dt_up, pos_label=1, average="binary")
recall_rf = recall_score(Y_test, y_rf, pos_label=1, average="binary")
recall_rf_up = recall_score(Y_test, y_rf_up, pos_label=1, average="binary")
recall_base = recall_score(Y_test, y_rf_base, pos_label=1, average="binary")
recall_base_up = recall_score(Y_test, y_rf_base_up, pos_label=1, average="binary")

print("recall lr:", recall_lr)
print("recall lr up:", recall_lr_up)
print("recall dt:", recall_dt)
print("recall dt up:", recall_dt_up)
print("recall rf:", recall_rf)
print("recall rf up:", recall_rf_up)
print("recall base:", recall_base)
print("recall base up:", recall_base_up)

recall lr: 0.5477477477477477
recall lr up: 0.7927927927927928
recall dt: 0.527927927927928
recall dt up: 0.5117117117117117
recall rf: 0.4702702702702703
recall rf up: 0.5351351351351351
recall base: 0.4774774774774775
recall base up: 0.7801801801801802

In [63]:
## AUC
y_lr = log_reg.predict_proba(X_test)[:, 1]
y_lr_up = log_reg_up.predict_proba(X_test)[:, 1]
y_dt = dt.predict_proba(X_test)[:, 1]
y_dt_up = dt_up.predict_proba(X_test)[:, 1]
y_rf = rf.predict_proba(X_test)[:, 1]
y_rf_up = rf_up.predict_proba(X_test)[:, 1]
y_rf_base = rf_base.predict_proba(X_test)[:, 1]
y_rf_base_up = rf_base_up.predict_proba(X_test)[:, 1]

In [64]:
from sklearn.metrics import roc_auc_score
auc_lr = roc_auc_score(Y_test, y_lr)
auc_lr_up = roc_auc_score(Y_test, y_lr_up)
auc_dt = roc_auc_score(Y_test, y_dt)
auc_dt_up = roc_auc_score(Y_test, y_dt_up)
auc_rf = roc_auc_score(Y_test, y_rf)
auc_rf_up = roc_auc_score(Y_test, y_rf_up)
auc_base = roc_auc_score(Y_test, y_rf_base)
auc_base_up = roc_auc_score(Y_test, y_rf_base_up)

print("auc lr:", auc_lr)
print("auc lr up:", auc_lr_up)
print("auc dt:", auc_dt)
print("auc dt up:", auc_dt_up)
print("auc rf:", auc_rf)
print("auc rf up:", auc_rf_up)
print("auc base:", auc_base)
print("auc base up:", auc_base_up)

auc lr: 0.8433880826163784
auc lr up: 0.8431783552040786
auc dt: 0.6610086613945134
auc dt up: 0.6677755569073898
auc rf: 0.8156803105356161
auc rf up: 0.8113090582543958
auc base: 0.8475716230700154
auc base up: 0.8440908432548304